### ISSUE TITLE
Setup test.

### ISSUE THREAD

**Issue by wasuken** [maetaro/junta#6]
@maetaro「やれ」
@wasuken「はい...」

**Comment by wasuken** [comment]
バックエンドはpytest、
フロントエンドはjestとenzymeっすかね。
バックエンドは取り急ぎで入れときました。
フロントエンドはこれからやりますが、ESLintとこんふりそうなのがちょっといやですね...。

**Comment by maetaro** [comment]
あざっす
jestでしょうねえ
